config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flowers
  resources :bees
  resources :hives
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bee.rb
class Bee < ApplicationRecord
  belongs_to :hive
  has_many :bee_flowers
  has_many :flowers, through: :bee_flowers

  validates :name, uniqueness: true

end

app/models/bee_flower.rb
class BeeFlower < ApplicationRecord
  belongs_to :bee
  belongs_to :flower
end

app/models/flower.rb
class Flower < ApplicationRecord
    has_many :bee_flowers
    has_many :bees, through: :bee_flowers

    validates :name, presence: true, uniqueness: true
    validates :color, presence: true
    validates :pollen_capacity, presence: true, numericality: {greater_than_or_equal_to: 0, only_integer: true}
end

app/models/hive.rb
class Hive < ApplicationRecord
    has_many :bees

    validates :name, uniqueness: true, presence: true
    validates :honey_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bees_controller.rb
class BeesController < ApplicationController
  before_action :set_bee, only: [:show, :edit, :update, :destroy]
  before_action :set_hives, only: [:new, :edit]

  def index
    @bees = Bee.all
  end

  def new
    @bee = Bee.new
  end

  def create
    @bee = Bee.create(bee_params)
    if @bee.valid?
      redirect_to @bee
    else
      flash[:errors] = @bee.errors.full_messages
      redirect_to new_bee_path
    end
  end

  def show

  end

  def edit

  end

  def update
    @bee.update(bee_params)
    if @bee.valid?
      redirect_to @bee
    else
      flash[:errors] = @bee.errors.full_messages
      redirect_to edit_bee_path(@bee)
    end
  end

  def destroy
    @bee.destroy
    redirect_to bees_path
  end

  private
  def bee_params
    params.require(:bee).permit(:name, :category, :queen, :hive_id, flower_ids: [])
  end

  def set_bee
    @bee = Bee.find(params[:id])
  end

  def set_hives
    @hives = Hive.all.sort_by { |h| h.name }
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: [:show, :edit, :update, :destroy]
  before_action :set_bees, only:[:new, :edit]

  def index
    @flowers = Flower.all
  end

  def show
      @bees = @flower.bees
  end

  def new
    @flower = Flower.new
  end

  def create
    @flower = Flower.create(flower_params)
      if @flower.valid?
        redirect_to @flower
      else
        flash[:errors] =  @flower.errors.full_messages
        redirect_to new_flower_path
      end
  end

  def edit
  end

  def update
    @flower.update(flower_params)
      if @flower.valid?
        redirect_to @flower
      else
        flash[:errors] = @flower.errors.full_messages
        redirect_to edit_flower_path(@flower)
      end
  end

  def destroy
    @flower.destroy
    redirect_to flowers_path
  end

  private

  def flower_params
    params.require(:flower).permit(:name, :color, :pollen_capacity, bee_ids: [])
  end

  def set_flower
    @flower = Flower.find(params[:id])
  end

  def set_bees
      @bees = Bee.all
  end

end

app/controllers/hives_controller.rb
class HivesController < ApplicationController
    before_action :set_hive, only: [:show, :edit, :update, :delete]
    before_action :set_bees, only:[:new, :edit]

    def index
        @hives = Hive.all
    end

    def show
        @bees = @hive.bees
    end

    def new
        @hive = Hive.new
    end

    def edit
    end

    def create
        hive = Hive.create(hive_params)
        if hive.valid?
            redirect_to hive
        else
            flash[:errors] = hive.errors.full_messages
            redirect_to new_hive_path
        end
    end

    def update
        @hive.update(hive_params)
        if @hive.valid?
            redirect_to @hive
        else
            flash[:errors] = @hive.errors.full_messages
            redirect_to edit_hive_path
        end
    end

    def delete
        @hive.destroy
        redirect_to hives_path
    end

    private
        def set_hive
            @hive = Hive.find(params[:id])
        end

        def hive_params
            params.require(:hive).permit(:name, :honey_type,:bee_ids [])
        end

        def set_bees
            @bees = Bee.all
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bees_helper.rb
module BeesHelper
end

app/helpers/hives_helper.rb
module HivesHelper
end

app/views/bees/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @bee do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :queen %>
  <%= f.check_box :queen %>
  <%= f.collection_select :hive_id, @hives, :id, :name%>
  <%= f.submit %>
<% end %>

app/views/bees/edit.html.erb
<h1>Edit yo beez</h1>

<%= render 'form' %>

<%= form_tag "/bees/:id", method: 'delete' do %>
  <%= submit_tag "REMOVE UR STRIPEZ" %>
<% end %>

app/views/bees/index.html.erb
<h1>The Bees in the Kingdom</h1>

<%= link_to "Spawn new Bee", new_bee_path %>

<ul>
  <% @bees.each do |bee| %>
    <li><%= link_to bee.name, bee %></li>
  <% end %>
</ul>

app/views/bees/new.html.erb
<h1> Create new bee </h1>

<%= render "form" %><br>

<%= link_to "Go back", bees_path %>

app/views/bees/show.html.erb
<h1><%= @bee.name %></h1>
<h2><%= @bee.category %></h2>

<p>I live at <%= link_to @bee.hive.name, @bee.hive %></p>

<label>But I work at: </label><br>
<ul>
  <% @bee.flowers.each do |flower| %>
    <li><%= link_to flower.name, flower %></li>
  <% end %>
</ul>

<%= link_to "Back to all Bees", bees_path %>
<%= link_to "Edit this Bee", edit_bee_path(@bee) %>

app/views/flowers/_form.html.erb
<%= render "errors/error" %>

<%= form_for @flower do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.label :pollen_capacity %>
  <%= f.text_field :pollen_capacity %>

  <%= f.collection_check_boxes(:bee_ids, @bees, :id, :name) %>

  <%= f.submit %>

<% end %>

app/views/flowers/edit.html.erb
<h1>Edit a Flower</h1>

<%= link_to "Go Back", @flower %>

<%= render "form" %>


<%= form_tag flower_path(@flower), method: "delete" do %>
  <%= submit_tag "Delete Flower"%>
<% end %>

app/views/flowers/index.html.erb
<h1>All the Flowers</h1>

<%= link_to "Make new Flower", new_flower_path %>

<ul>
  <% @flowers.each do |flower| %>
    <li><%= link_to flower.name, flower %></li>
  <% end %>
</ul>

app/views/flowers/new.html.erb
<h1>Make New Flower</h1>

<%= link_to "Go Back", flowers_path %>

<%= render "form" %>

app/views/flowers/show.html.erb
<h1><%= @flower.name %></h1>
<h3><%= @flower.color %></h3>
<h3><%= @flower.pollen_capacity %></h3>

<ul>
    <%@bees.each do |bee|%>
        <li> <%= link_to bee.name, bee %> </li> 
    <% end %>
</ul>


<%= link_to "All Flowers", flowers_path %>
<%= link_to "Edit Flower", edit_flower_path %>

app/views/hives/_footer.html.erb
<br>
<%= link_to "See all Hives!", hives_path %><br>
<%= link_to "Add new Hive", new_hive_path %>

app/views/hives/_form.html.erb
<% if flash[:errors] && flash[:errors].length > 0  %>
    <ul><%  flash[:errors].each do |error| %>
        <li> <%= error %></li>
        <% end %>
    </ul>
<% end  %>



<%= form_for @hive do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :honey_type %>
    <%= f.text_field :honey_type %><br>
    <%= f.label "Bees:" %>
    <%= f.collection_check_boxes :bee_ids, @bees, :id, :name %><br>
    <%= f.submit %>
<% end %>

app/views/hives/edit.html.erb
<h1>Edit Hive:</h1>

<%= render "form" %>
<br>
<%= link_to "Go back!", @hive %>

<%= form_tag hive_path(@hive), method "delete" do %>
    <%= submit_tag "Delete Hive" %>
    <% end %>

<%= render "footer" %>

app/views/hives/index.html.erb
<h1>All Hives</h1>

<ul><% @hives.each do |hive| %>
    <li><%= link_to hive.name, hive %> | <%= hive.honey_type %></li>
    <% end  %>
</ul>

 <%= link_to "Create new Hive", new_hive_path %>

app/views/hives/new.html.erb
<h1>Create a new Hive</h1>

<%= render "form" %>

<%= render "footer" %>

app/views/hives/show.html.erb
<h1><%= @hive.name %></h1>

<p>This is a lovely hive. It specialises in <%= @hive.honey_type %> honey.</p>

<p>The bees that belong to this hive are:</p>

<ul><% @bees.each do |bee| %>
    <li><%= link_to bee.name, bee %></li>
    <% end %>
    </ul>
<%= render "footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garden</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>